### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by johnhorner** [syui/atr#2]
I can post text but when I try to post an image (`./atr img-upload 50aba5a408054.jpg`) I get this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `cid`", line: 1, column: 140)', src/main.rs:676:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Version 0.0.1 running on OSX Catalina 10.15.7 (19H2026).

I have set RUST_BACKTRACE but I'm getting the same error, no details.

**Comment by syui** [comment]
yes, It stopped working due to a change in api.

**Comment by syui** [comment]
support img

```sh
# img-upload & img-post
$ link=`atr img-upload ~/icloud/icon/ai_circle.png|jq -r .blob.ref.'"$link"'`;atr img-post test -l $link
```
